name: webfly
description: "WebFly is like webf go / expo go, focused on rendering target web pages"
homepage: "https://github.com/vidlg/webfly"
publish_to: 'none'
version: 0.3.1+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webf: 0.24.9
  webf_cupertino_ui: ^0.4.1
  webf_share: ^1.1.0
  webf_sqflite: ^1.0.1
  mobile_scanner: ^7.1.4
  shared_preferences: ^2.5.4
  signals: ^6.3.0
  signals_flutter: ^6.3.0
  flutter_hooks: ^0.21.3
  go_router: ^17.0.1
  logger: ^2.6.2
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  permission_handler: ^12.0.1
  flutter_blue_plus: ^2.1.0
  anyhow: ^3.0.1
  catcher_2: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/gen/
    - assets/use_cases/index.html
    - assets/use_cases/favicon.ico
    - assets/use_cases/assets/

gen-logo:
  source: assets/logo/webfly_logo.png
  output_dir: assets/gen
  target_size: 256
  padding: 60

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/gen/webfly_logo_dark.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/gen/webfly_logo_dark.png"
  image_path_android_light: "assets/gen/webfly_logo_light.png"
  adaptive_icon_background_light: "#ffffff"
  adaptive_icon_foreground_light: "assets/gen/webfly_logo_light.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/gen/webfly_logo_light.png
  color_dark: "#121212"
  image_dark: assets/gen/webfly_logo_dark.png
  android: true
  ios: false
  fullscreen: false
  android_gravity: center
  android_12:
    color: "#ffffff"
    image: assets/gen/webfly_logo_light.png
    color_dark: "#121212"
    image_dark: assets/gen/webfly_logo_dark.png
    branding: assets/gen/webfly_branding_light.png
    branding_dark: assets/gen/webfly_branding_dark.png
